CREATE TABLE `mob_bultos_leidos` (
  `idlectura` INT(11) NOT NULL AUTO_INCREMENT,
  `idpedido` INT(11) NOT NULL,
  `nro_remito` VARCHAR(100) NOT NULL,
  `nro_bulto` VARCHAR(100) NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idlectura`)
) ENGINE=INNODB AUTO_INCREMENT=160 DEFAULT CHARSET=utf8;